/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsItTransformationRouteImport } from './routes/solutions.it-transformation'
import { Route as SolutionsLogisticsRouteImport } from './routes/solutions.logistics'
import { Route as SolutionsSourcingRouteImport } from './routes/solutions.sourcing'
import { Route as SolutionsSupplyChainFinanceRouteImport } from './routes/solutions.supply-chain-finance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsItTransformationRoute =
  SolutionsItTransformationRouteImport.update({
    id: '/solutions/it-transformation',
    path: '/solutions/it-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsLogisticsRoute = SolutionsLogisticsRouteImport.update({
  id: '/solutions/logistics',
  path: '/solutions/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSourcingRoute = SolutionsSourcingRouteImport.update({
  id: '/solutions/sourcing',
  path: '/solutions/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSupplyChainFinanceRoute =
  SolutionsSupplyChainFinanceRouteImport.update({
    id: '/solutions/supply-chain-finance',
    path: '/solutions/supply-chain-finance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solutions/it-transformation': typeof SolutionsItTransformationRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/sourcing': typeof SolutionsSourcingRoute
  '/solutions/supply-chain-finance': typeof SolutionsSupplyChainFinanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solutions/it-transformation': typeof SolutionsItTransformationRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/sourcing': typeof SolutionsSourcingRoute
  '/solutions/supply-chain-finance': typeof SolutionsSupplyChainFinanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solutions/it-transformation': typeof SolutionsItTransformationRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/sourcing': typeof SolutionsSourcingRoute
  '/solutions/supply-chain-finance': typeof SolutionsSupplyChainFinanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/solutions/it-transformation'
    | '/solutions/logistics'
    | '/solutions/sourcing'
    | '/solutions/supply-chain-finance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/solutions/it-transformation'
    | '/solutions/logistics'
    | '/solutions/sourcing'
    | '/solutions/supply-chain-finance'
  id:
    | '__root__'
    | '/'
    | '/solutions/it-transformation'
    | '/solutions/logistics'
    | '/solutions/sourcing'
    | '/solutions/supply-chain-finance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolutionsItTransformationRoute: typeof SolutionsItTransformationRoute
  SolutionsLogisticsRoute: typeof SolutionsLogisticsRoute
  SolutionsSourcingRoute: typeof SolutionsSourcingRoute
  SolutionsSupplyChainFinanceRoute: typeof SolutionsSupplyChainFinanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/it-transformation': {
      id: '/solutions/it-transformation'
      path: '/solutions/it-transformation'
      fullPath: '/solutions/it-transformation'
      preLoaderRoute: typeof SolutionsItTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/logistics': {
      id: '/solutions/logistics'
      path: '/solutions/logistics'
      fullPath: '/solutions/logistics'
      preLoaderRoute: typeof SolutionsLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/sourcing': {
      id: '/solutions/sourcing'
      path: '/solutions/sourcing'
      fullPath: '/solutions/sourcing'
      preLoaderRoute: typeof SolutionsSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/supply-chain-finance': {
      id: '/solutions/supply-chain-finance'
      path: '/solutions/supply-chain-finance'
      fullPath: '/solutions/supply-chain-finance'
      preLoaderRoute: typeof SolutionsSupplyChainFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolutionsItTransformationRoute: SolutionsItTransformationRoute,
  SolutionsLogisticsRoute: SolutionsLogisticsRoute,
  SolutionsSourcingRoute: SolutionsSourcingRoute,
  SolutionsSupplyChainFinanceRoute: SolutionsSupplyChainFinanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
